export type WorkCategory = "Branding" | "Web" | "Marketing" | "PR" | "Campaign";

export type CaseStudy = {
  slug: string;
  client: string;
  sector: string;
  category: WorkCategory;
  title: string;
  summary: string;
  scope: string[];
  result: { metric: string; label: string }[];
  accent: string;
  featured?: boolean;
  /** How big the tile renders in the randomized grid. */
  tile?: "sm" | "md" | "lg";
};

export const WORK: CaseStudy[] = [
  {
    slug: "allegiance-education",
    client: "Allegiance Education",
    sector: "Edtech · Test Prep",
    category: "Branding",
    title: "From a classroom to a national institute.",
    summary:
      "Repositioned through identity, messaging, and admissions assets that look the part of a top-tier institute.",
    scope: ["Brand Strategy", "Identity", "Print"],
    result: [
      { metric: "+62%", label: "admissions" },
      { metric: "3 cities", label: "rolled out" },
    ],
    accent: "from-amber-300/40 to-teal-400/30",
    featured: true,
    tile: "lg",
  },
  {
    slug: "tax2win",
    client: "Tax2Win",
    sector: "Fintech · Tax Filing",
    category: "Campaign",
    title: "Owning filing season, end-to-end.",
    summary:
      "Hindi-first creative for billboards, performance ads, and landing pages around one promise: file with a real CA.",
    scope: ["Campaign", "OOH", "Performance"],
    result: [
      { metric: "3.2×", label: "leads" },
      { metric: "−34%", label: "CAC" },
    ],
    accent: "from-emerald-300/40 to-teal-500/30",
    featured: true,
    tile: "md",
  },
  {
    slug: "yug-vaastra",
    client: "Yug Vaastra",
    sector: "D2C · Fashion (Tolaram)",
    category: "Branding",
    title: "Heritage that ships.",
    summary:
      "A heritage-meets-modern identity for Tolaram Group's flagship label — circular monogram, premium stationery, and packaging.",
    scope: ["Identity", "Stationery", "Packaging"],
    result: [
      { metric: "Day-1", label: "wholesale ready" },
      { metric: "+48%", label: "IG growth" },
    ],
    accent: "from-rose-300/40 to-teal-500/30",
    featured: true,
    tile: "lg",
  },
  {
    slug: "unlock-career",
    client: "Unlock Career",
    sector: "Career · Coaching",
    category: "Web",
    title: "A site that books calls on autopilot.",
    summary:
      "Replaced a templated build with a custom site, sharper offer page, and calendar-led booking flow.",
    scope: ["UI/UX", "Development", "CRO"],
    result: [
      { metric: "5.4%", label: "visit-to-call" },
      { metric: "−1.8s", label: "LCP" },
    ],
    accent: "from-sky-300/40 to-teal-500/30",
    tile: "md",
  },
  {
    slug: "jaipur-health-festival",
    client: "Jaipur Health Festival",
    sector: "Events · Healthcare",
    category: "PR",
    title: "Owned media that sold out a city-scale festival.",
    summary:
      "Press launch with Dainik Bhaskar and Dainik Jagran, founder bylines, and a unified visual system across stage, OOH, and social.",
    scope: ["PR", "Press", "Event Identity"],
    result: [
      { metric: "12+", label: "tier-1 features" },
      { metric: "Sold out", label: "partnerships" },
    ],
    accent: "from-orange-300/40 to-teal-500/30",
    tile: "md",
  },
  {
    slug: "dns-pointers",
    client: "DNS Pointers",
    sector: "B2B · Consulting",
    category: "Branding",
    title: "A precise mark for a precise consultancy.",
    summary:
      "Wordmark, target-arrow monogram, and LinkedIn-first founder branding that helped close two enterprise pilots.",
    scope: ["Identity", "Founder Branding", "LinkedIn"],
    result: [
      { metric: "2", label: "enterprise pilots" },
      { metric: "+5.7k", label: "founder followers" },
    ],
    accent: "from-amber-300/40 to-teal-500/30",
    tile: "sm",
  },
  {
    slug: "volimy",
    client: "Volimy",
    sector: "D2C · Wellness",
    category: "Branding",
    title: "A debossed mark for a category-creator.",
    summary: "Custom wordmark, signage program, and packaging system for a launch SKU.",
    scope: ["Identity", "Signage"],
    result: [{ metric: "Launch", label: "ready in 9 wks" }],
    accent: "from-stone-300/40 to-teal-400/30",
    tile: "sm",
  },
  {
    slug: "mission-tee",
    client: "Mission TEE",
    sector: "Public · Education",
    category: "Campaign",
    title: "Technical education, made aspirational.",
    summary: "Identity + creative platform for a public-sector empowerment mission.",
    scope: ["Identity", "Campaign"],
    result: [{ metric: "3 states", label: "rolled out" }],
    accent: "from-orange-300/40 to-teal-500/30",
    tile: "md",
  },
  {
    slug: "amritam",
    client: "Amritam",
    sector: "D2C · Wellness",
    category: "Branding",
    title: "A mark with a leaf — and a memory.",
    summary: "Wordmark, packaging system, and a content engine for an ayurveda-first FMCG.",
    scope: ["Identity", "Packaging"],
    result: [{ metric: "Day-1", label: "wholesale ready" }],
    accent: "from-emerald-300/40 to-teal-500/30",
    tile: "sm",
  },
  {
    slug: "woocom-pro",
    client: "WooCom Pro",
    sector: "Tech · SaaS",
    category: "Web",
    title: "A SaaS site that talks like an operator.",
    summary: "Repositioning + product UI for a WooCommerce store-manager.",
    scope: ["Strategy", "UI/UX"],
    result: [{ metric: "+212%", label: "trial signups" }],
    accent: "from-violet-300/40 to-teal-500/30",
    tile: "md",
  },
  {
    slug: "wealth-wisdom",
    client: "Wealth Wisdom Consultants",
    sector: "Fintech · Advisory",
    category: "Branding",
    title: "A rebrand from W to W+.",
    summary: "Refreshed identity, stationery, and a calmer trust-led palette.",
    scope: ["Identity Refresh"],
    result: [{ metric: "Q1", label: "AUM uplift" }],
    accent: "from-sky-300/40 to-teal-500/30",
    tile: "sm",
  },
  {
    slug: "tagore-engineering-college",
    client: "Tagore Engineering College",
    sector: "Edtech · Higher Ed",
    category: "Branding",
    title: "A crest worth its lineage.",
    summary: "Crest, prospectus system, and admissions creative.",
    scope: ["Identity", "Print"],
    result: [{ metric: "Cohort", label: "filled in 6 wks" }],
    accent: "from-stone-300/40 to-teal-500/30",
    tile: "sm",
  },
  {
    slug: "a2z-smart-spaces",
    client: "A2Z Smart Spaces",
    sector: "Real Estate · Smart Cities",
    category: "Branding",
    title: "Identity + collateral for smart-city services.",
    summary: "Mark, business stationery, and proposal system.",
    scope: ["Identity", "Collateral"],
    result: [{ metric: "Pitch", label: "win rate +" }],
    accent: "from-rose-300/40 to-teal-500/30",
    tile: "sm",
  },
  {
    slug: "nutrition-simplified",
    client: "Nutrition Simplified",
    sector: "Healthcare · D2C",
    category: "Branding",
    title: "An apple — but make it a system.",
    summary: "Wordmark, packaging, and a content series for the launch.",
    scope: ["Identity", "Packaging", "Content"],
    result: [{ metric: "Launch", label: "in 7 wks" }],
    accent: "from-emerald-300/40 to-teal-500/30",
    tile: "md",
  },
  {
    slug: "iteks",
    client: "iTeks Technology",
    sector: "Tech · IT services",
    category: "Branding",
    title: "A wordmark with a wink.",
    summary: "Identity refresh + a deck system for sales motion.",
    scope: ["Identity", "Sales Deck"],
    result: [{ metric: "Pitch deck", label: "halved meeting count" }],
    accent: "from-sky-300/40 to-teal-500/30",
    tile: "sm",
  },
  {
    slug: "pure-earth",
    client: "PureEarth",
    sector: "Public · Sustainability",
    category: "Branding",
    title: "An identity that reads as a promise.",
    summary: "Mark, applications, and a launch microsite.",
    scope: ["Identity", "Web"],
    result: [{ metric: "+33%", label: "donor sign-ups" }],
    accent: "from-emerald-300/40 to-teal-500/30",
    tile: "md",
  },
  {
    slug: "basta",
    client: "Basta",
    sector: "D2C · Fashion",
    category: "Branding",
    title: "Clutches. Handbags. Personality.",
    summary: "Wordmark + retail look for a bold accessories label.",
    scope: ["Identity", "Retail"],
    result: [{ metric: "Day-30", label: "shelf-ready" }],
    accent: "from-rose-300/40 to-teal-500/30",
    tile: "sm",
  },
  {
    slug: "masterchef-rajasthan",
    client: "Masterchef Rajasthan",
    sector: "Media · TV",
    category: "Campaign",
    title: "A regional flagship made cinematic.",
    summary: "Show identity, on-air package, and social cuts for Season 2.",
    scope: ["Identity", "On-air"],
    result: [{ metric: "S2", label: "highest TVR" }],
    accent: "from-amber-300/40 to-teal-500/30",
    tile: "md",
  },
];

export const FEATURED_WORK = WORK.filter((w) => w.featured);
